@echo off
title Starting Aura Life OS...
echo ==========================================
echo       STARTING AURA LIFE OS
echo ==========================================
echo Launching development server...
start /b cmd /c "npm run dev"
echo Waiting 5 seconds for server startup...
timeout /t 5 >nul
echo Opening http://localhost:5173 in browser...
start http://localhost:5173
